# Generated by Django 6.0.2 on 2026-09-05 07:56

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('symbol', models.CharField(db_index=True, max_length=30, unique=True)),
                ('category', models.CharField(choices=[('fixed_deposit', 'Fixed Deposit'), ('recurring_deposit', 'Recurring Deposit'), ('bond', 'Bond'), ('mutual_fund', 'Mutual Fund'), ('etf', 'ETF'), ('commodity', 'Commodity'), ('forex', 'Forex'), ('crypto', 'Crypto'), ('other', 'Other')], db_index=True, default='fixed_deposit', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('interest_rate', models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='Advertised annual rate shown on the landing card.', max_digits=6)),
                ('tenure_months', models.PositiveIntegerField(default=12)),
                ('min_investment', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('max_investment', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('price_source', models.CharField(choices=[('manual', 'Admin-managed'), ('feed', 'Live feed')], db_index=True, default='manual', max_length=10)),
                ('current_price', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('previous_close', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('day_high', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('day_low', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('feed_volatility_percent', models.DecimalField(decimal_places=3, default=Decimal('0.250'), max_digits=5)),
                ('price_updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'instruments',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Issuer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('short_name', models.CharField(blank=True, max_length=40)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='issuers/')),
                ('country', models.CharField(blank=True, max_length=100)),
                ('website', models.URLField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'issuers',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PriceTick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=4, max_digits=18)),
                ('recorded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'price_ticks',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
