# Generated by Django 6.0.2 on 2026-09-05 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instruments', '0001_initial'),
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='roi_plan',
            field=models.ForeignKey(blank=True, help_text='Leave blank to select a plan from the invested amount instead.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instruments', to='investments.roiplan'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='issuer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instruments', to='instruments.issuer'),
        ),
        migrations.AddField(
            model_name='pricetick',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticks', to='instruments.instrument'),
        ),
        migrations.AddIndex(
            model_name='instrument',
            index=models.Index(fields=['is_active', 'is_featured'], name='instruments_is_acti_ad1753_idx'),
        ),
        migrations.AddIndex(
            model_name='pricetick',
            index=models.Index(fields=['instrument', '-recorded_at'], name='price_ticks_instrum_2c34c5_idx'),
        ),
    ]
