# Generated by Django 6.0.2 on 2026-09-05 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='currency',
            field=models.CharField(default='INR', max_length=10),
        ),
    ]
