# Generated by Django 6.0.2 on 2026-09-06 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0003_alter_instrument_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
    ]
