# Generated by Django 6.0.2 on 2026-09-05 07:56

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MlmLevelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(unique=True)),
                ('label', models.CharField(blank=True, max_length=60)),
                ('deposit_percent', models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='Percent of a downline deposit paid to this level.', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('roi_percent', models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='Percent of a downline monthly ROI payout paid to this level.', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('min_direct_referrals', models.PositiveIntegerField(default=0, help_text='Direct referrals required to unlock this level.')),
                ('min_self_investment', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Active principal the upline must hold to earn at this level.', max_digits=18)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'mlm_level_configs',
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.PositiveIntegerField(db_index=True)),
                ('trigger', models.CharField(choices=[('deposit', 'Deposit'), ('roi', 'ROI Payout'), ('investment', 'Investment Purchase')], db_index=True, max_length=20)),
                ('base_amount', models.DecimalField(decimal_places=2, help_text='Amount the percent applied to.', max_digits=18)),
                ('percent', models.DecimalField(decimal_places=3, max_digits=6)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('skipped', 'Skipped (unqualified)'), ('reversed', 'Reversed')], db_index=True, default='paid', max_length=20)),
                ('skip_reason', models.CharField(blank=True, max_length=200)),
                ('reference_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('reference_type', models.CharField(blank=True, max_length=40)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('earner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions_earned', to=settings.AUTH_USER_MODEL)),
                ('source_user', models.ForeignKey(help_text='The downline member whose activity produced this commission.', on_delete=django.db.models.deletion.CASCADE, related_name='commissions_generated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mlm_commissions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['earner', 'status', 'created_at'], name='mlm_commiss_earner__95b953_idx'), models.Index(fields=['source_user', 'created_at'], name='mlm_commiss_source__cfc822_idx')],
                'constraints': [models.UniqueConstraint(fields=('earner', 'trigger', 'reference_id'), name='uniq_commission_per_earner_event')],
            },
        ),
    ]
