# Generated by Django 6.0.2 on 2026-09-10 08:34

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank for an open-ended top slab.', max_digits=18, null=True)),
                ('tenure_months', models.PositiveIntegerField(default=12, help_text='How many monthly payments a sponsor receives.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'referral_plans',
                'ordering': ['display_order', 'min_amount'],
            },
        ),
        migrations.CreateModel(
            name='ReferralPlanMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_index', models.PositiveIntegerField(help_text='1 = the first month after the deposit.')),
                ('percent', models.DecimalField(decimal_places=3, help_text="Percent of the referral's deposit paid to their sponsor this month.", max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='months', to='mlm.referralplan')),
            ],
            options={
                'db_table': 'referral_plan_months',
                'ordering': ['plan', 'month_index'],
            },
        ),
        migrations.DeleteModel(
            name='MlmLevelConfig',
        ),
        migrations.AddField(
            model_name='commission',
            name='month_index',
            field=models.PositiveIntegerField(default=0, help_text="Which month of the referral's investment this paid for."),
        ),
        migrations.AlterField(
            model_name='commission',
            name='base_amount',
            field=models.DecimalField(decimal_places=2, help_text="The referral's deposit, which the percent applied to.", max_digits=18),
        ),
        migrations.AlterField(
            model_name='commission',
            name='level',
            field=models.PositiveIntegerField(db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='commission',
            name='source_user',
            field=models.ForeignKey(help_text='The referral whose deposit produced this payment.', on_delete=django.db.models.deletion.CASCADE, related_name='commissions_generated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commission',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('skipped', 'Skipped'), ('reversed', 'Reversed')], db_index=True, default='paid', max_length=20),
        ),
        migrations.AlterField(
            model_name='commission',
            name='trigger',
            field=models.CharField(choices=[('referral', 'Monthly referral')], db_index=True, default='referral', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='referralplanmonth',
            constraint=models.UniqueConstraint(fields=('plan', 'month_index'), name='uniq_referral_plan_month'),
        ),
    ]
