# Generated by Django 6.0.2 on 2026-09-10 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycdocument',
            name='proof_type',
            field=models.CharField(blank=True, choices=[('aadhaar', 'Aadhaar card'), ('pan', 'PAN card'), ('national_id', 'National ID')], help_text='Which identity document this is. Only set on the ID pages.', max_length=20),
        ),
    ]
