# Generated by Django 6.0.2 on 2026-09-05 07:56

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentChannel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('channel_type', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank Transfer'), ('upi', 'UPI'), ('crypto', 'Crypto')], max_length=20)),
                ('account_name', models.CharField(blank=True, max_length=120)),
                ('account_number', models.CharField(blank=True, max_length=64)),
                ('bank_name', models.CharField(blank=True, max_length=120)),
                ('ifsc_code', models.CharField(blank=True, max_length=20)),
                ('branch', models.CharField(blank=True, max_length=120)),
                ('upi_id', models.CharField(blank=True, max_length=100)),
                ('wallet_address', models.CharField(blank=True, max_length=200)),
                ('network', models.CharField(blank=True, max_length=40)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='payment_qr/')),
                ('contact_person', models.CharField(blank=True, max_length=120)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('office_address', models.TextField(blank=True)),
                ('instructions', models.TextField(blank=True)),
                ('min_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'payment_channels',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank Transfer'), ('upi', 'UPI'), ('crypto', 'Crypto')], db_index=True, max_length=20)),
                ('user_message', models.TextField(blank=True)),
                ('reference_no', models.CharField(blank=True, help_text='UTR / txn id / cash receipt no.', max_length=120)),
                ('proof', models.ImageField(blank=True, null=True, upload_to='deposit_proofs/')),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('admin_note', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposits_reviewed', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to=settings.AUTH_USER_MODEL)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposits', to='wallet.paymentchannel')),
            ],
            options={
                'db_table': 'deposits',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='deposits_status_564167_idx')],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tx_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('roi', 'ROI Payout'), ('commission', 'Referral Commission'), ('investment', 'Investment Purchase'), ('principal_return', 'Principal Returned'), ('adjustment', 'Admin Adjustment'), ('fee', 'Fee')], db_index=True, max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=18)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('reference_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('reference_type', models.CharField(blank=True, max_length=40)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'tx_type', 'created_at'], name='transaction_user_id_539dd2_idx')],
            },
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Gross amount debited from the wallet.', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('fee', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('net_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='What the user actually receives, after fee.', max_digits=18)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank Transfer'), ('upi', 'UPI'), ('crypto', 'Crypto')], db_index=True, max_length=20)),
                ('payout_details', models.JSONField(blank=True, default=dict)),
                ('user_message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('admin_note', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('payout_reference', models.CharField(blank=True, max_length=120)),
                ('payout_proof', models.ImageField(blank=True, null=True, upload_to='payout_proofs/')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawals_reviewed', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'withdrawals',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='withdrawals_status_7d3043_idx')],
            },
        ),
    ]
