# Generated by Django 6.0.2 on 2026-09-06 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_alter_deposit_currency_alter_withdrawal_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
    ]
