/**
 * The emoji set, generated from the Unicode data tables.
 *
 * Written out rather than pulled from a package: a picker library brings a
 * runtime, a stylesheet and its own theme to argue with, for what is in the
 * end a list of characters and their names. The names are what make the search
 * box work — without them sixteen hundred emoji is a scroll, not a picker.
 *
 * The symbol group is deliberately curated. Most of the dingbat and
 * miscellaneous-symbol blocks are not emoji at all, and a text arrow sitting in
 * a reaction row reads as a rendering fault rather than a choice.
 */

export type EmojiEntry = {
  /** The character itself. */
  c: string;
  /** Its Unicode name, lowercased — this is what search matches on. */
  n: string;
};

export type EmojiGroup = { label: string; items: EmojiEntry[] };

/** The row that opens with the menu, before anyone reaches for the picker. */
export const QUICK_REACTIONS = ['👍', '❤️', '😂', '😮', '😢', '🙏'];

export const EMOJI_GROUPS: EmojiGroup[] = [
  {
    label: 'Smileys',
    items: [
      { c: '😀', n: 'grinning face' },
      { c: '😁', n: 'grinning face with smiling eyes' },
      { c: '😂', n: 'face with tears of joy' },
      { c: '😃', n: 'smiling face with open mouth' },
      { c: '😄', n: 'smiling face with open mouth and smiling eyes' },
      { c: '😅', n: 'smiling face with open mouth and cold sweat' },
      { c: '😆', n: 'smiling face with open mouth and tightly-closed eyes' },
      { c: '😇', n: 'smiling face with halo' },
      { c: '😈', n: 'smiling face with horns' },
      { c: '😉', n: 'winking face' },
      { c: '😊', n: 'smiling face with smiling eyes' },
      { c: '😋', n: 'face savouring delicious food' },
      { c: '😌', n: 'relieved face' },
      { c: '😍', n: 'smiling face with heart-shaped eyes' },
      { c: '😎', n: 'smiling face with sunglasses' },
      { c: '😏', n: 'smirking face' },
      { c: '😐', n: 'neutral face' },
      { c: '😑', n: 'expressionless face' },
      { c: '😒', n: 'unamused face' },
      { c: '😓', n: 'face with cold sweat' },
      { c: '😔', n: 'pensive face' },
      { c: '😕', n: 'confused face' },
      { c: '😖', n: 'confounded face' },
      { c: '😗', n: 'kissing face' },
      { c: '😘', n: 'face throwing a kiss' },
      { c: '😙', n: 'kissing face with smiling eyes' },
      { c: '😚', n: 'kissing face with closed eyes' },
      { c: '😛', n: 'face with stuck-out tongue' },
      { c: '😜', n: 'face with stuck-out tongue and winking eye' },
      { c: '😝', n: 'face with stuck-out tongue and tightly-closed eyes' },
      { c: '😞', n: 'disappointed face' },
      { c: '😟', n: 'worried face' },
      { c: '😠', n: 'angry face' },
      { c: '😡', n: 'pouting face' },
      { c: '😢', n: 'crying face' },
      { c: '😣', n: 'persevering face' },
      { c: '😤', n: 'face with look of triumph' },
      { c: '😥', n: 'disappointed but relieved face' },
      { c: '😦', n: 'frowning face with open mouth' },
      { c: '😧', n: 'anguished face' },
      { c: '😨', n: 'fearful face' },
      { c: '😩', n: 'weary face' },
      { c: '😪', n: 'sleepy face' },
      { c: '😫', n: 'tired face' },
      { c: '😬', n: 'grimacing face' },
      { c: '😭', n: 'loudly crying face' },
      { c: '😮', n: 'face with open mouth' },
      { c: '😯', n: 'hushed face' },
      { c: '😰', n: 'face with open mouth and cold sweat' },
      { c: '😱', n: 'face screaming in fear' },
      { c: '😲', n: 'astonished face' },
      { c: '😳', n: 'flushed face' },
      { c: '😴', n: 'sleeping face' },
      { c: '😵', n: 'dizzy face' },
      { c: '😶', n: 'face without mouth' },
      { c: '😷', n: 'face with medical mask' },
      { c: '😸', n: 'grinning cat face with smiling eyes' },
      { c: '😹', n: 'cat face with tears of joy' },
      { c: '😺', n: 'smiling cat face with open mouth' },
      { c: '😻', n: 'smiling cat face with heart-shaped eyes' },
      { c: '😼', n: 'cat face with wry smile' },
      { c: '😽', n: 'kissing cat face with closed eyes' },
      { c: '😾', n: 'pouting cat face' },
      { c: '😿', n: 'crying cat face' },
      { c: '🙀', n: 'weary cat face' },
      { c: '🙁', n: 'slightly frowning face' },
      { c: '🙂', n: 'slightly smiling face' },
      { c: '🙃', n: 'upside-down face' },
      { c: '🙄', n: 'face with rolling eyes' },
      { c: '🙅', n: 'face with no good gesture' },
      { c: '🙆', n: 'face with ok gesture' },
      { c: '🙇', n: 'person bowing deeply' },
      { c: '🙈', n: 'see-no-evil monkey' },
      { c: '🙉', n: 'hear-no-evil monkey' },
      { c: '🙊', n: 'speak-no-evil monkey' },
      { c: '🙋', n: 'happy person raising one hand' },
      { c: '🙌', n: 'person raising both hands in celebration' },
      { c: '🙍', n: 'person frowning' },
      { c: '🙎', n: 'person with pouting face' },
      { c: '🙏', n: 'person with folded hands' },
      { c: '🤐', n: 'zipper-mouth face' },
      { c: '🤑', n: 'money-mouth face' },
      { c: '🤒', n: 'face with thermometer' },
      { c: '🤓', n: 'nerd face' },
      { c: '🤔', n: 'thinking face' },
      { c: '🤕', n: 'face with head-bandage' },
      { c: '🤖', n: 'robot face' },
      { c: '🤗', n: 'hugging face' },
      { c: '🤘', n: 'sign of the horns' },
      { c: '🤙', n: 'call me hand' },
      { c: '🤚', n: 'raised back of hand' },
      { c: '🤛', n: 'left-facing fist' },
      { c: '🤜', n: 'right-facing fist' },
      { c: '🤝', n: 'handshake' },
      { c: '🤞', n: 'hand with index and middle fingers crossed' },
      { c: '🤟', n: 'i love you hand sign' },
      { c: '🤠', n: 'face with cowboy hat' },
      { c: '🤡', n: 'clown face' },
      { c: '🤢', n: 'nauseated face' },
      { c: '🤣', n: 'rolling on the floor laughing' },
      { c: '🤤', n: 'drooling face' },
      { c: '🤥', n: 'lying face' },
      { c: '🤦', n: 'face palm' },
      { c: '🤧', n: 'sneezing face' },
      { c: '🤨', n: 'face with one eyebrow raised' },
      { c: '🤩', n: 'grinning face with star eyes' },
      { c: '🤪', n: 'grinning face with one large and one small eye' },
      { c: '🤫', n: 'face with finger covering closed lips' },
      { c: '🤬', n: 'serious face with symbols covering mouth' },
      { c: '🤭', n: 'smiling face with smiling eyes and hand covering mouth' },
      { c: '🤮', n: 'face with open mouth vomiting' },
      { c: '🤯', n: 'shocked face with exploding head' },
      { c: '🤰', n: 'pregnant woman' },
      { c: '🤱', n: 'breast-feeding' },
      { c: '🤲', n: 'palms up together' },
      { c: '🤳', n: 'selfie' },
      { c: '🤴', n: 'prince' },
      { c: '🤵', n: 'man in tuxedo' },
      { c: '🤶', n: 'mother christmas' },
      { c: '🤷', n: 'shrug' },
      { c: '🤸', n: 'person doing cartwheel' },
      { c: '🤹', n: 'juggling' },
      { c: '🤺', n: 'fencer' },
      { c: '🥰', n: 'smiling face with smiling eyes and three hearts' },
      { c: '🥱', n: 'yawning face' },
      { c: '🥲', n: 'smiling face with tear' },
      { c: '🥳', n: 'face with party horn and party hat' },
      { c: '🥴', n: 'face with uneven eyes and wavy mouth' },
      { c: '🥵', n: 'overheated face' },
      { c: '🥶', n: 'freezing face' },
      { c: '🥷', n: 'ninja' },
      { c: '🥸', n: 'disguised face' },
      { c: '🥹', n: 'face holding back tears' },
      { c: '🥺', n: 'face with pleading eyes' },
      { c: '💀', n: 'skull' },
      { c: '💩', n: 'pile of poo' },
      { c: '☺', n: 'white smiling face' },
    ],
  },
  {
    label: 'People',
    items: [
      { c: '👀', n: 'eyes' },
      { c: '👁', n: 'eye' },
      { c: '👂', n: 'ear' },
      { c: '👃', n: 'nose' },
      { c: '👄', n: 'mouth' },
      { c: '👅', n: 'tongue' },
      { c: '👆', n: 'white up pointing backhand index' },
      { c: '👇', n: 'white down pointing backhand index' },
      { c: '👈', n: 'white left pointing backhand index' },
      { c: '👉', n: 'white right pointing backhand index' },
      { c: '👊', n: 'fisted hand sign' },
      { c: '👋', n: 'waving hand sign' },
      { c: '👌', n: 'ok hand sign' },
      { c: '👍', n: 'thumbs up sign' },
      { c: '👎', n: 'thumbs down sign' },
      { c: '👏', n: 'clapping hands sign' },
      { c: '👐', n: 'open hands sign' },
      { c: '👤', n: 'bust in silhouette' },
      { c: '👥', n: 'busts in silhouette' },
      { c: '👦', n: 'boy' },
      { c: '👧', n: 'girl' },
      { c: '👨', n: 'man' },
      { c: '👩', n: 'woman' },
      { c: '👪', n: 'family' },
      { c: '👫', n: 'man and woman holding hands' },
      { c: '👬', n: 'two men holding hands' },
      { c: '👭', n: 'two women holding hands' },
      { c: '👮', n: 'police officer' },
      { c: '👯', n: 'woman with bunny ears' },
      { c: '👰', n: 'bride with veil' },
      { c: '👱', n: 'person with blond hair' },
      { c: '👲', n: 'man with gua pi mao' },
      { c: '👳', n: 'man with turban' },
      { c: '👴', n: 'older man' },
      { c: '👵', n: 'older woman' },
      { c: '👶', n: 'baby' },
      { c: '👷', n: 'construction worker' },
      { c: '👸', n: 'princess' },
      { c: '👹', n: 'japanese ogre' },
      { c: '👺', n: 'japanese goblin' },
      { c: '👻', n: 'ghost' },
      { c: '👼', n: 'baby angel' },
      { c: '👽', n: 'extraterrestrial alien' },
      { c: '👾', n: 'alien monster' },
      { c: '👿', n: 'imp' },
      { c: '💁', n: 'information desk person' },
      { c: '💂', n: 'guardsman' },
      { c: '💃', n: 'dancer' },
      { c: '💄', n: 'lipstick' },
      { c: '💅', n: 'nail polish' },
      { c: '💆', n: 'face massage' },
      { c: '💇', n: 'haircut' },
      { c: '🤼', n: 'wrestlers' },
      { c: '🤽', n: 'water polo' },
      { c: '🤾', n: 'handball' },
      { c: '🤿', n: 'diving mask' },
      { c: '🥀', n: 'wilted flower' },
      { c: '🥁', n: 'drum with drumsticks' },
      { c: '🥂', n: 'clinking glasses' },
      { c: '🥃', n: 'tumbler glass' },
      { c: '🥄', n: 'spoon' },
      { c: '🥅', n: 'goal net' },
      { c: '🧑', n: 'adult' },
      { c: '🧒', n: 'child' },
      { c: '🧓', n: 'older adult' },
      { c: '🧔', n: 'bearded person' },
      { c: '🧕', n: 'person with headscarf' },
      { c: '🧖', n: 'person in steamy room' },
      { c: '🧗', n: 'person climbing' },
      { c: '🧘', n: 'person in lotus position' },
      { c: '🧙', n: 'mage' },
      { c: '🧚', n: 'fairy' },
      { c: '🧛', n: 'vampire' },
      { c: '🧜', n: 'merperson' },
      { c: '🧝', n: 'elf' },
      { c: '🧞', n: 'genie' },
      { c: '🧟', n: 'zombie' },
      { c: '✊', n: 'raised fist' },
      { c: '✋', n: 'raised hand' },
      { c: '✌', n: 'victory hand' },
      { c: '✍', n: 'writing hand' },
      { c: '🫰', n: 'hand with index finger and thumb crossed' },
      { c: '🫱', n: 'rightwards hand' },
      { c: '🫲', n: 'leftwards hand' },
      { c: '🫳', n: 'palm down hand' },
      { c: '🫴', n: 'palm up hand' },
      { c: '🫵', n: 'index pointing at the viewer' },
      { c: '🫶', n: 'heart hands' },
      { c: '🫷', n: 'leftwards pushing hand' },
      { c: '🫸', n: 'rightwards pushing hand' },
      { c: '🕴', n: 'man in business suit levitating' },
      { c: '🕵', n: 'sleuth or spy' },
      { c: '🚶', n: 'pedestrian' },
    ],
  },
  {
    label: 'Nature',
    items: [
      { c: '🐀', n: 'rat' },
      { c: '🐁', n: 'mouse' },
      { c: '🐂', n: 'ox' },
      { c: '🐃', n: 'water buffalo' },
      { c: '🐄', n: 'cow' },
      { c: '🐅', n: 'tiger' },
      { c: '🐆', n: 'leopard' },
      { c: '🐇', n: 'rabbit' },
      { c: '🐈', n: 'cat' },
      { c: '🐉', n: 'dragon' },
      { c: '🐊', n: 'crocodile' },
      { c: '🐋', n: 'whale' },
      { c: '🐌', n: 'snail' },
      { c: '🐍', n: 'snake' },
      { c: '🐎', n: 'horse' },
      { c: '🐏', n: 'ram' },
      { c: '🐐', n: 'goat' },
      { c: '🐑', n: 'sheep' },
      { c: '🐒', n: 'monkey' },
      { c: '🐓', n: 'rooster' },
      { c: '🐔', n: 'chicken' },
      { c: '🐕', n: 'dog' },
      { c: '🐖', n: 'pig' },
      { c: '🐗', n: 'boar' },
      { c: '🐘', n: 'elephant' },
      { c: '🐙', n: 'octopus' },
      { c: '🐚', n: 'spiral shell' },
      { c: '🐛', n: 'bug' },
      { c: '🐜', n: 'ant' },
      { c: '🐝', n: 'honeybee' },
      { c: '🐞', n: 'lady beetle' },
      { c: '🐟', n: 'fish' },
      { c: '🐠', n: 'tropical fish' },
      { c: '🐡', n: 'blowfish' },
      { c: '🐢', n: 'turtle' },
      { c: '🐣', n: 'hatching chick' },
      { c: '🐤', n: 'baby chick' },
      { c: '🐥', n: 'front-facing baby chick' },
      { c: '🐦', n: 'bird' },
      { c: '🐧', n: 'penguin' },
      { c: '🐨', n: 'koala' },
      { c: '🐩', n: 'poodle' },
      { c: '🐪', n: 'dromedary camel' },
      { c: '🐫', n: 'bactrian camel' },
      { c: '🐬', n: 'dolphin' },
      { c: '🐭', n: 'mouse face' },
      { c: '🐮', n: 'cow face' },
      { c: '🐯', n: 'tiger face' },
      { c: '🐰', n: 'rabbit face' },
      { c: '🐱', n: 'cat face' },
      { c: '🐲', n: 'dragon face' },
      { c: '🐳', n: 'spouting whale' },
      { c: '🐴', n: 'horse face' },
      { c: '🐵', n: 'monkey face' },
      { c: '🐶', n: 'dog face' },
      { c: '🐷', n: 'pig face' },
      { c: '🐸', n: 'frog face' },
      { c: '🐹', n: 'hamster face' },
      { c: '🐺', n: 'wolf face' },
      { c: '🐻', n: 'bear face' },
      { c: '🐼', n: 'panda face' },
      { c: '🐽', n: 'pig nose' },
      { c: '🐾', n: 'paw prints' },
      { c: '🐿', n: 'chipmunk' },
      { c: '🦀', n: 'crab' },
      { c: '🦁', n: 'lion face' },
      { c: '🦂', n: 'scorpion' },
      { c: '🦃', n: 'turkey' },
      { c: '🦄', n: 'unicorn face' },
      { c: '🦅', n: 'eagle' },
      { c: '🦆', n: 'duck' },
      { c: '🦇', n: 'bat' },
      { c: '🦈', n: 'shark' },
      { c: '🦉', n: 'owl' },
      { c: '🦊', n: 'fox face' },
      { c: '🦋', n: 'butterfly' },
      { c: '🦌', n: 'deer' },
      { c: '🦍', n: 'gorilla' },
      { c: '🦎', n: 'lizard' },
      { c: '🦏', n: 'rhinoceros' },
      { c: '🦐', n: 'shrimp' },
      { c: '🦑', n: 'squid' },
      { c: '🦒', n: 'giraffe face' },
      { c: '🦓', n: 'zebra face' },
      { c: '🦔', n: 'hedgehog' },
      { c: '🦕', n: 'sauropod' },
      { c: '🦖', n: 't-rex' },
      { c: '🦗', n: 'cricket' },
      { c: '🦘', n: 'kangaroo' },
      { c: '🦙', n: 'llama' },
      { c: '🦚', n: 'peacock' },
      { c: '🦛', n: 'hippopotamus' },
      { c: '🦜', n: 'parrot' },
      { c: '🦝', n: 'raccoon' },
      { c: '🦞', n: 'lobster' },
      { c: '🦟', n: 'mosquito' },
      { c: '🦠', n: 'microbe' },
      { c: '🦡', n: 'badger' },
      { c: '🦢', n: 'swan' },
      { c: '🦣', n: 'mammoth' },
      { c: '🦤', n: 'dodo' },
      { c: '🦥', n: 'sloth' },
      { c: '🦦', n: 'otter' },
      { c: '🦧', n: 'orangutan' },
      { c: '🦨', n: 'skunk' },
      { c: '🦩', n: 'flamingo' },
      { c: '🦪', n: 'oyster' },
      { c: '🦫', n: 'beaver' },
      { c: '🦬', n: 'bison' },
      { c: '🦭', n: 'seal' },
      { c: '🦮', n: 'guide dog' },
      { c: '🌰', n: 'chestnut' },
      { c: '🌱', n: 'seedling' },
      { c: '🌲', n: 'evergreen tree' },
      { c: '🌳', n: 'deciduous tree' },
      { c: '🌴', n: 'palm tree' },
      { c: '🌵', n: 'cactus' },
      { c: '🌶', n: 'hot pepper' },
      { c: '🌷', n: 'tulip' },
      { c: '🌸', n: 'cherry blossom' },
      { c: '🌹', n: 'rose' },
      { c: '🌺', n: 'hibiscus' },
      { c: '🌻', n: 'sunflower' },
      { c: '🌼', n: 'blossom' },
      { c: '🌽', n: 'ear of maize' },
      { c: '🌾', n: 'ear of rice' },
      { c: '🌿', n: 'herb' },
      { c: '🍀', n: 'four leaf clover' },
      { c: '🍁', n: 'maple leaf' },
      { c: '🍂', n: 'fallen leaf' },
      { c: '🍃', n: 'leaf fluttering in wind' },
      { c: '🌀', n: 'cyclone' },
      { c: '🌁', n: 'foggy' },
      { c: '🌂', n: 'closed umbrella' },
      { c: '🌃', n: 'night with stars' },
      { c: '🌄', n: 'sunrise over mountains' },
      { c: '🌅', n: 'sunrise' },
      { c: '🌆', n: 'cityscape at dusk' },
      { c: '🌇', n: 'sunset over buildings' },
      { c: '🌈', n: 'rainbow' },
      { c: '🌉', n: 'bridge at night' },
      { c: '🌊', n: 'water wave' },
      { c: '🌋', n: 'volcano' },
      { c: '🌌', n: 'milky way' },
      { c: '🌍', n: 'earth globe europe-africa' },
      { c: '🌎', n: 'earth globe americas' },
      { c: '🌏', n: 'earth globe asia-australia' },
      { c: '🌐', n: 'globe with meridians' },
      { c: '🌑', n: 'new moon symbol' },
      { c: '🌒', n: 'waxing crescent moon symbol' },
      { c: '🌓', n: 'first quarter moon symbol' },
      { c: '🌔', n: 'waxing gibbous moon symbol' },
      { c: '🌕', n: 'full moon symbol' },
      { c: '🌖', n: 'waning gibbous moon symbol' },
      { c: '🌗', n: 'last quarter moon symbol' },
      { c: '🌘', n: 'waning crescent moon symbol' },
      { c: '🌙', n: 'crescent moon' },
      { c: '🌚', n: 'new moon with face' },
      { c: '🌛', n: 'first quarter moon with face' },
      { c: '🌜', n: 'last quarter moon with face' },
      { c: '🌝', n: 'full moon with face' },
      { c: '🌞', n: 'sun with face' },
      { c: '🌟', n: 'glowing star' },
      { c: '🌠', n: 'shooting star' },
      { c: '🌡', n: 'thermometer' },
      { c: '🌢', n: 'black droplet' },
      { c: '🌣', n: 'white sun' },
      { c: '🌤', n: 'white sun with small cloud' },
      { c: '🌥', n: 'white sun behind cloud' },
      { c: '🌦', n: 'white sun behind cloud with rain' },
      { c: '🌧', n: 'cloud with rain' },
      { c: '🌨', n: 'cloud with snow' },
      { c: '🌩', n: 'cloud with lightning' },
      { c: '🌪', n: 'cloud with tornado' },
      { c: '🌫', n: 'fog' },
      { c: '🌬', n: 'wind blowing face' },
    ],
  },
  {
    label: 'Food',
    items: [
      { c: '🍄', n: 'mushroom' },
      { c: '🍅', n: 'tomato' },
      { c: '🍆', n: 'aubergine' },
      { c: '🍇', n: 'grapes' },
      { c: '🍈', n: 'melon' },
      { c: '🍉', n: 'watermelon' },
      { c: '🍊', n: 'tangerine' },
      { c: '🍋', n: 'lemon' },
      { c: '🍌', n: 'banana' },
      { c: '🍍', n: 'pineapple' },
      { c: '🍎', n: 'red apple' },
      { c: '🍏', n: 'green apple' },
      { c: '🍐', n: 'pear' },
      { c: '🍑', n: 'peach' },
      { c: '🍒', n: 'cherries' },
      { c: '🍓', n: 'strawberry' },
      { c: '🍔', n: 'hamburger' },
      { c: '🍕', n: 'slice of pizza' },
      { c: '🍖', n: 'meat on bone' },
      { c: '🍗', n: 'poultry leg' },
      { c: '🍘', n: 'rice cracker' },
      { c: '🍙', n: 'rice ball' },
      { c: '🍚', n: 'cooked rice' },
      { c: '🍛', n: 'curry and rice' },
      { c: '🍜', n: 'steaming bowl' },
      { c: '🍝', n: 'spaghetti' },
      { c: '🍞', n: 'bread' },
      { c: '🍟', n: 'french fries' },
      { c: '🍠', n: 'roasted sweet potato' },
      { c: '🍡', n: 'dango' },
      { c: '🍢', n: 'oden' },
      { c: '🍣', n: 'sushi' },
      { c: '🍤', n: 'fried shrimp' },
      { c: '🍥', n: 'fish cake with swirl design' },
      { c: '🍦', n: 'soft ice cream' },
      { c: '🍧', n: 'shaved ice' },
      { c: '🍨', n: 'ice cream' },
      { c: '🍩', n: 'doughnut' },
      { c: '🍪', n: 'cookie' },
      { c: '🍫', n: 'chocolate bar' },
      { c: '🍬', n: 'candy' },
      { c: '🍭', n: 'lollipop' },
      { c: '🍮', n: 'custard' },
      { c: '🍯', n: 'honey pot' },
      { c: '🍰', n: 'shortcake' },
      { c: '🍱', n: 'bento box' },
      { c: '🍲', n: 'pot of food' },
      { c: '🍳', n: 'cooking' },
      { c: '🍴', n: 'fork and knife' },
      { c: '🍵', n: 'teacup without handle' },
      { c: '🍶', n: 'sake bottle and cup' },
      { c: '🍷', n: 'wine glass' },
      { c: '🍸', n: 'cocktail glass' },
      { c: '🍹', n: 'tropical drink' },
      { c: '🍺', n: 'beer mug' },
      { c: '🍻', n: 'clinking beer mugs' },
      { c: '🍼', n: 'baby bottle' },
      { c: '🍽', n: 'fork and knife with plate' },
      { c: '🍾', n: 'bottle with popping cork' },
      { c: '🍿', n: 'popcorn' },
      { c: '🥐', n: 'croissant' },
      { c: '🥑', n: 'avocado' },
      { c: '🥒', n: 'cucumber' },
      { c: '🥓', n: 'bacon' },
      { c: '🥔', n: 'potato' },
      { c: '🥕', n: 'carrot' },
      { c: '🥖', n: 'baguette bread' },
      { c: '🥗', n: 'green salad' },
      { c: '🥘', n: 'shallow pan of food' },
      { c: '🥙', n: 'stuffed flatbread' },
      { c: '🥚', n: 'egg' },
      { c: '🥛', n: 'glass of milk' },
      { c: '🥜', n: 'peanuts' },
      { c: '🥝', n: 'kiwifruit' },
      { c: '🥞', n: 'pancakes' },
      { c: '🥟', n: 'dumpling' },
      { c: '🥠', n: 'fortune cookie' },
      { c: '🥡', n: 'takeout box' },
      { c: '🥢', n: 'chopsticks' },
      { c: '🥣', n: 'bowl with spoon' },
      { c: '🥤', n: 'cup with straw' },
      { c: '🥥', n: 'coconut' },
      { c: '🥦', n: 'broccoli' },
      { c: '🥧', n: 'pie' },
      { c: '🥨', n: 'pretzel' },
      { c: '🥩', n: 'cut of meat' },
      { c: '🥪', n: 'sandwich' },
      { c: '🥫', n: 'canned food' },
      { c: '🥬', n: 'leafy green' },
      { c: '🥭', n: 'mango' },
      { c: '🥮', n: 'moon cake' },
      { c: '🥯', n: 'bagel' },
      { c: '🧀', n: 'cheese wedge' },
      { c: '🧁', n: 'cupcake' },
      { c: '🧂', n: 'salt shaker' },
      { c: '🧃', n: 'beverage box' },
      { c: '🧄', n: 'garlic' },
      { c: '🧅', n: 'onion' },
      { c: '🧆', n: 'falafel' },
      { c: '🧇', n: 'waffle' },
      { c: '🧈', n: 'butter' },
      { c: '🧉', n: 'mate drink' },
      { c: '🧊', n: 'ice cube' },
      { c: '🧋', n: 'bubble tea' },
    ],
  },
  {
    label: 'Activity',
    items: [
      { c: '🎀', n: 'ribbon' },
      { c: '🎁', n: 'wrapped present' },
      { c: '🎂', n: 'birthday cake' },
      { c: '🎃', n: 'jack-o-lantern' },
      { c: '🎄', n: 'christmas tree' },
      { c: '🎅', n: 'father christmas' },
      { c: '🎆', n: 'fireworks' },
      { c: '🎇', n: 'firework sparkler' },
      { c: '🎈', n: 'balloon' },
      { c: '🎉', n: 'party popper' },
      { c: '🎊', n: 'confetti ball' },
      { c: '🎋', n: 'tanabata tree' },
      { c: '🎌', n: 'crossed flags' },
      { c: '🎍', n: 'pine decoration' },
      { c: '🎎', n: 'japanese dolls' },
      { c: '🎏', n: 'carp streamer' },
      { c: '🎐', n: 'wind chime' },
      { c: '🎑', n: 'moon viewing ceremony' },
      { c: '🎒', n: 'school satchel' },
      { c: '🎓', n: 'graduation cap' },
      { c: '🎔', n: 'heart with tip on the left' },
      { c: '🎕', n: 'bouquet of flowers' },
      { c: '🎖', n: 'military medal' },
      { c: '🎗', n: 'reminder ribbon' },
      { c: '🎘', n: 'musical keyboard with jacks' },
      { c: '🎙', n: 'studio microphone' },
      { c: '🎚', n: 'level slider' },
      { c: '🎛', n: 'control knobs' },
      { c: '🎜', n: 'beamed ascending musical notes' },
      { c: '🎝', n: 'beamed descending musical notes' },
      { c: '🎞', n: 'film frames' },
      { c: '🎟', n: 'admission tickets' },
      { c: '🎠', n: 'carousel horse' },
      { c: '🎡', n: 'ferris wheel' },
      { c: '🎢', n: 'roller coaster' },
      { c: '🎣', n: 'fishing pole and fish' },
      { c: '🎤', n: 'microphone' },
      { c: '🎥', n: 'movie camera' },
      { c: '🎦', n: 'cinema' },
      { c: '🎧', n: 'headphone' },
      { c: '🎨', n: 'artist palette' },
      { c: '🎩', n: 'top hat' },
      { c: '🎪', n: 'circus tent' },
      { c: '🎫', n: 'ticket' },
      { c: '🎬', n: 'clapper board' },
      { c: '🎭', n: 'performing arts' },
      { c: '🎮', n: 'video game' },
      { c: '🎯', n: 'direct hit' },
      { c: '🎰', n: 'slot machine' },
      { c: '🎱', n: 'billiards' },
      { c: '🎲', n: 'game die' },
      { c: '🎳', n: 'bowling' },
      { c: '🎴', n: 'flower playing cards' },
      { c: '🎵', n: 'musical note' },
      { c: '🎶', n: 'multiple musical notes' },
      { c: '🎷', n: 'saxophone' },
      { c: '🎸', n: 'guitar' },
      { c: '🎹', n: 'musical keyboard' },
      { c: '🎺', n: 'trumpet' },
      { c: '🎻', n: 'violin' },
      { c: '🎼', n: 'musical score' },
      { c: '🎽', n: 'running shirt with sash' },
      { c: '🎾', n: 'tennis racquet and ball' },
      { c: '🎿', n: 'ski and ski boot' },
      { c: '🏀', n: 'basketball and hoop' },
      { c: '🏁', n: 'chequered flag' },
      { c: '🏂', n: 'snowboarder' },
      { c: '🏃', n: 'runner' },
      { c: '🏄', n: 'surfer' },
      { c: '🏅', n: 'sports medal' },
      { c: '🏆', n: 'trophy' },
      { c: '🏇', n: 'horse racing' },
      { c: '🏈', n: 'american football' },
      { c: '🏉', n: 'rugby football' },
      { c: '🏊', n: 'swimmer' },
      { c: '🏋', n: 'weight lifter' },
      { c: '🏌', n: 'golfer' },
      { c: '🏍', n: 'racing motorcycle' },
      { c: '🏎', n: 'racing car' },
      { c: '🏏', n: 'cricket bat and ball' },
      { c: '🏐', n: 'volleyball' },
      { c: '🏑', n: 'field hockey stick and ball' },
      { c: '🏒', n: 'ice hockey stick and puck' },
      { c: '🏓', n: 'table tennis paddle and ball' },
      { c: '🏔', n: 'snow capped mountain' },
      { c: '🏕', n: 'camping' },
      { c: '🏖', n: 'beach with umbrella' },
      { c: '🏗', n: 'building construction' },
      { c: '🏘', n: 'house buildings' },
      { c: '🏙', n: 'cityscape' },
      { c: '🏚', n: 'derelict house building' },
      { c: '🏛', n: 'classical building' },
      { c: '🏜', n: 'desert' },
      { c: '🏝', n: 'desert island' },
      { c: '🏞', n: 'national park' },
      { c: '🏟', n: 'stadium' },
      { c: '🏠', n: 'house building' },
      { c: '🏡', n: 'house with garden' },
      { c: '🏢', n: 'office building' },
      { c: '🏣', n: 'japanese post office' },
      { c: '🏤', n: 'european post office' },
      { c: '🏥', n: 'hospital' },
      { c: '🏦', n: 'bank' },
      { c: '🏧', n: 'automated teller machine' },
      { c: '🏨', n: 'hotel' },
      { c: '🏩', n: 'love hotel' },
      { c: '🏪', n: 'convenience store' },
      { c: '🏫', n: 'school' },
      { c: '🏬', n: 'department store' },
      { c: '🏭', n: 'factory' },
      { c: '🏮', n: 'izakaya lantern' },
      { c: '🏯', n: 'japanese castle' },
      { c: '🏰', n: 'european castle' },
      { c: '🏱', n: 'white pennant' },
      { c: '🏲', n: 'black pennant' },
      { c: '🏳', n: 'waving white flag' },
      { c: '🏴', n: 'waving black flag' },
      { c: '🏵', n: 'rosette' },
      { c: '🏶', n: 'black rosette' },
      { c: '🏷', n: 'label' },
      { c: '🏸', n: 'badminton racquet and shuttlecock' },
      { c: '🏹', n: 'bow and arrow' },
      { c: '🏺', n: 'amphora' },
      { c: '⚽', n: 'soccer ball' },
      { c: '⚾', n: 'baseball' },
      { c: '🥇', n: 'first place medal' },
      { c: '🥈', n: 'second place medal' },
      { c: '🥉', n: 'third place medal' },
      { c: '🥊', n: 'boxing glove' },
      { c: '🥋', n: 'martial arts uniform' },
      { c: '🥌', n: 'curling stone' },
      { c: '🥍', n: 'lacrosse stick and ball' },
      { c: '🥎', n: 'softball' },
      { c: '🥏', n: 'flying disc' },
    ],
  },
  {
    label: 'Travel',
    items: [
      { c: '🚀', n: 'rocket' },
      { c: '🚁', n: 'helicopter' },
      { c: '🚂', n: 'steam locomotive' },
      { c: '🚃', n: 'railway car' },
      { c: '🚄', n: 'high-speed train' },
      { c: '🚅', n: 'high-speed train with bullet nose' },
      { c: '🚆', n: 'train' },
      { c: '🚇', n: 'metro' },
      { c: '🚈', n: 'light rail' },
      { c: '🚉', n: 'station' },
      { c: '🚊', n: 'tram' },
      { c: '🚋', n: 'tram car' },
      { c: '🚌', n: 'bus' },
      { c: '🚍', n: 'oncoming bus' },
      { c: '🚎', n: 'trolleybus' },
      { c: '🚏', n: 'bus stop' },
      { c: '🚐', n: 'minibus' },
      { c: '🚑', n: 'ambulance' },
      { c: '🚒', n: 'fire engine' },
      { c: '🚓', n: 'police car' },
      { c: '🚔', n: 'oncoming police car' },
      { c: '🚕', n: 'taxi' },
      { c: '🚖', n: 'oncoming taxi' },
      { c: '🚗', n: 'automobile' },
      { c: '🚘', n: 'oncoming automobile' },
      { c: '🚙', n: 'recreational vehicle' },
      { c: '🚚', n: 'delivery truck' },
      { c: '🚛', n: 'articulated lorry' },
      { c: '🚜', n: 'tractor' },
      { c: '🚝', n: 'monorail' },
      { c: '🚞', n: 'mountain railway' },
      { c: '🚟', n: 'suspension railway' },
      { c: '🚠', n: 'mountain cableway' },
      { c: '🚡', n: 'aerial tramway' },
      { c: '🚢', n: 'ship' },
      { c: '🚣', n: 'rowboat' },
      { c: '🚤', n: 'speedboat' },
      { c: '🚥', n: 'horizontal traffic light' },
      { c: '🚦', n: 'vertical traffic light' },
      { c: '🚧', n: 'construction sign' },
      { c: '🚨', n: 'police cars revolving light' },
      { c: '🚩', n: 'triangular flag on post' },
      { c: '🚪', n: 'door' },
      { c: '🚫', n: 'no entry sign' },
      { c: '🚬', n: 'smoking symbol' },
      { c: '🚭', n: 'no smoking symbol' },
      { c: '🚮', n: 'put litter in its place symbol' },
      { c: '🚯', n: 'do not litter symbol' },
      { c: '🚰', n: 'potable water symbol' },
      { c: '🚱', n: 'non-potable water symbol' },
      { c: '🚲', n: 'bicycle' },
      { c: '🚳', n: 'no bicycles' },
      { c: '🚴', n: 'bicyclist' },
      { c: '🚵', n: 'mountain bicyclist' },
      { c: '🚷', n: 'no pedestrians' },
      { c: '🚸', n: 'children crossing' },
      { c: '🚹', n: 'mens symbol' },
      { c: '🚺', n: 'womens symbol' },
      { c: '🚻', n: 'restroom' },
      { c: '🚼', n: 'baby symbol' },
      { c: '🚽', n: 'toilet' },
      { c: '🚾', n: 'water closet' },
      { c: '🚿', n: 'shower' },
      { c: '🛀', n: 'bath' },
      { c: '🛁', n: 'bathtub' },
      { c: '🛂', n: 'passport control' },
      { c: '🛃', n: 'customs' },
      { c: '🛄', n: 'baggage claim' },
      { c: '🛅', n: 'left luggage' },
      { c: '🗺', n: 'world map' },
      { c: '🗻', n: 'mount fuji' },
      { c: '🗼', n: 'tokyo tower' },
      { c: '🗽', n: 'statue of liberty' },
      { c: '🗾', n: 'silhouette of japan' },
      { c: '🗿', n: 'moyai' },
      { c: '✈', n: 'airplane' },
      { c: '⛲', n: 'fountain' },
      { c: '⛳', n: 'flag in hole' },
      { c: '⛴', n: 'ferry' },
      { c: '⛵', n: 'sailboat' },
      { c: '⛺', n: 'tent' },
      { c: '⛽', n: 'fuel pump' },
    ],
  },
  {
    label: 'Objects',
    items: [
      { c: '💠', n: 'diamond shape with a dot inside' },
      { c: '💡', n: 'electric light bulb' },
      { c: '💢', n: 'anger symbol' },
      { c: '💣', n: 'bomb' },
      { c: '💤', n: 'sleeping symbol' },
      { c: '💥', n: 'collision symbol' },
      { c: '💦', n: 'splashing sweat symbol' },
      { c: '💧', n: 'droplet' },
      { c: '💨', n: 'dash symbol' },
      { c: '💪', n: 'flexed biceps' },
      { c: '💫', n: 'dizzy symbol' },
      { c: '💬', n: 'speech balloon' },
      { c: '💭', n: 'thought balloon' },
      { c: '💮', n: 'white flower' },
      { c: '💯', n: 'hundred points symbol' },
      { c: '💰', n: 'money bag' },
      { c: '💱', n: 'currency exchange' },
      { c: '💲', n: 'heavy dollar sign' },
      { c: '💳', n: 'credit card' },
      { c: '💴', n: 'banknote with yen sign' },
      { c: '💵', n: 'banknote with dollar sign' },
      { c: '💶', n: 'banknote with euro sign' },
      { c: '💷', n: 'banknote with pound sign' },
      { c: '💸', n: 'money with wings' },
      { c: '💹', n: 'chart with upwards trend and yen sign' },
      { c: '💺', n: 'seat' },
      { c: '💻', n: 'personal computer' },
      { c: '💼', n: 'briefcase' },
      { c: '💽', n: 'minidisc' },
      { c: '💾', n: 'floppy disk' },
      { c: '💿', n: 'optical disc' },
      { c: '📀', n: 'dvd' },
      { c: '📁', n: 'file folder' },
      { c: '📂', n: 'open file folder' },
      { c: '📃', n: 'page with curl' },
      { c: '📄', n: 'page facing up' },
      { c: '📅', n: 'calendar' },
      { c: '📆', n: 'tear-off calendar' },
      { c: '📇', n: 'card index' },
      { c: '📈', n: 'chart with upwards trend' },
      { c: '📉', n: 'chart with downwards trend' },
      { c: '📊', n: 'bar chart' },
      { c: '📋', n: 'clipboard' },
      { c: '📌', n: 'pushpin' },
      { c: '📍', n: 'round pushpin' },
      { c: '📎', n: 'paperclip' },
      { c: '📏', n: 'straight ruler' },
      { c: '📐', n: 'triangular ruler' },
      { c: '📑', n: 'bookmark tabs' },
      { c: '📒', n: 'ledger' },
      { c: '📓', n: 'notebook' },
      { c: '📔', n: 'notebook with decorative cover' },
      { c: '📕', n: 'closed book' },
      { c: '📖', n: 'open book' },
      { c: '📗', n: 'green book' },
      { c: '📘', n: 'blue book' },
      { c: '📙', n: 'orange book' },
      { c: '📚', n: 'books' },
      { c: '📛', n: 'name badge' },
      { c: '📜', n: 'scroll' },
      { c: '📝', n: 'memo' },
      { c: '📞', n: 'telephone receiver' },
      { c: '📟', n: 'pager' },
      { c: '📠', n: 'fax machine' },
      { c: '📡', n: 'satellite antenna' },
      { c: '📢', n: 'public address loudspeaker' },
      { c: '📣', n: 'cheering megaphone' },
      { c: '📤', n: 'outbox tray' },
      { c: '📥', n: 'inbox tray' },
      { c: '📦', n: 'package' },
      { c: '📧', n: 'e-mail symbol' },
      { c: '📨', n: 'incoming envelope' },
      { c: '📩', n: 'envelope with downwards arrow above' },
      { c: '📪', n: 'closed mailbox with lowered flag' },
      { c: '📫', n: 'closed mailbox with raised flag' },
      { c: '📬', n: 'open mailbox with raised flag' },
      { c: '📭', n: 'open mailbox with lowered flag' },
      { c: '📮', n: 'postbox' },
      { c: '📯', n: 'postal horn' },
      { c: '📰', n: 'newspaper' },
      { c: '📱', n: 'mobile phone' },
      { c: '📲', n: 'mobile phone with rightwards arrow at left' },
      { c: '📳', n: 'vibration mode' },
      { c: '📴', n: 'mobile phone off' },
      { c: '📵', n: 'no mobile phones' },
      { c: '📶', n: 'antenna with bars' },
      { c: '📷', n: 'camera' },
      { c: '📸', n: 'camera with flash' },
      { c: '📹', n: 'video camera' },
      { c: '📺', n: 'television' },
      { c: '📻', n: 'radio' },
      { c: '📼', n: 'videocassette' },
      { c: '📽', n: 'film projector' },
      { c: '📾', n: 'portable stereo' },
      { c: '📿', n: 'prayer beads' },
      { c: '🔀', n: 'twisted rightwards arrows' },
      { c: '🔁', n: 'clockwise rightwards and leftwards open circle arrows' },
      { c: '🔂', n: 'clockwise rightwards and leftwards open circle arrows with circled one overlay' },
      { c: '🔃', n: 'clockwise downwards and upwards open circle arrows' },
      { c: '🔄', n: 'anticlockwise downwards and upwards open circle arrows' },
      { c: '🔅', n: 'low brightness symbol' },
      { c: '🔆', n: 'high brightness symbol' },
      { c: '🔇', n: 'speaker with cancellation stroke' },
      { c: '🔈', n: 'speaker' },
      { c: '🔉', n: 'speaker with one sound wave' },
      { c: '🔊', n: 'speaker with three sound waves' },
      { c: '🔋', n: 'battery' },
      { c: '🔌', n: 'electric plug' },
      { c: '🔍', n: 'left-pointing magnifying glass' },
      { c: '🔎', n: 'right-pointing magnifying glass' },
      { c: '🔏', n: 'lock with ink pen' },
      { c: '🔐', n: 'closed lock with key' },
      { c: '🔑', n: 'key' },
      { c: '🔒', n: 'lock' },
      { c: '🔓', n: 'open lock' },
      { c: '🔔', n: 'bell' },
      { c: '🔕', n: 'bell with cancellation stroke' },
      { c: '🔖', n: 'bookmark' },
      { c: '🔗', n: 'link symbol' },
      { c: '🔘', n: 'radio button' },
      { c: '🔙', n: 'back with leftwards arrow above' },
      { c: '🔚', n: 'end with leftwards arrow above' },
      { c: '🔛', n: 'on with exclamation mark with left right arrow above' },
      { c: '🔜', n: 'soon with rightwards arrow above' },
      { c: '🔝', n: 'top with upwards arrow above' },
      { c: '🔞', n: 'no one under eighteen symbol' },
      { c: '🔟', n: 'keycap ten' },
      { c: '🔠', n: 'input symbol for latin capital letters' },
      { c: '🔡', n: 'input symbol for latin small letters' },
      { c: '🔢', n: 'input symbol for numbers' },
      { c: '🔣', n: 'input symbol for symbols' },
      { c: '🔤', n: 'input symbol for latin letters' },
      { c: '🔥', n: 'fire' },
      { c: '🔦', n: 'electric torch' },
      { c: '🔧', n: 'wrench' },
      { c: '🔨', n: 'hammer' },
      { c: '🔩', n: 'nut and bolt' },
      { c: '🔪', n: 'hocho' },
      { c: '🔫', n: 'pistol' },
      { c: '🔬', n: 'microscope' },
      { c: '🔭', n: 'telescope' },
      { c: '🔮', n: 'crystal ball' },
      { c: '🔯', n: 'six pointed star with middle dot' },
      { c: '🔰', n: 'japanese symbol for beginner' },
      { c: '🔱', n: 'trident emblem' },
      { c: '🔲', n: 'black square button' },
      { c: '🔳', n: 'white square button' },
      { c: '🔴', n: 'large red circle' },
      { c: '🔵', n: 'large blue circle' },
      { c: '🔶', n: 'large orange diamond' },
      { c: '🔷', n: 'large blue diamond' },
      { c: '🔸', n: 'small orange diamond' },
      { c: '🔹', n: 'small blue diamond' },
      { c: '🔺', n: 'up-pointing red triangle' },
      { c: '🔻', n: 'down-pointing red triangle' },
      { c: '🔼', n: 'up-pointing small red triangle' },
      { c: '🔽', n: 'down-pointing small red triangle' },
      { c: '🧰', n: 'toolbox' },
      { c: '🧱', n: 'brick' },
      { c: '🧲', n: 'magnet' },
      { c: '🧳', n: 'luggage' },
      { c: '🧴', n: 'lotion bottle' },
      { c: '🧵', n: 'spool of thread' },
      { c: '🧶', n: 'ball of yarn' },
      { c: '🧷', n: 'safety pin' },
      { c: '🧸', n: 'teddy bear' },
      { c: '🧹', n: 'broom' },
      { c: '🧺', n: 'basket' },
      { c: '🧻', n: 'roll of paper' },
      { c: '🧼', n: 'bar of soap' },
      { c: '🧽', n: 'sponge' },
      { c: '🧾', n: 'receipt' },
      { c: '🧿', n: 'nazar amulet' },
      { c: '🩰', n: 'ballet shoes' },
      { c: '🩱', n: 'one-piece swimsuit' },
      { c: '🩲', n: 'briefs' },
      { c: '🩳', n: 'shorts' },
      { c: '🩴', n: 'thong sandal' },
      { c: '🩵', n: 'light blue heart' },
      { c: '🩶', n: 'grey heart' },
      { c: '🩷', n: 'pink heart' },
      { c: '🩸', n: 'drop of blood' },
      { c: '🩹', n: 'adhesive bandage' },
      { c: '🩺', n: 'stethoscope' },
      { c: '🩻', n: 'x-ray' },
      { c: '🩼', n: 'crutch' },
      { c: '🪀', n: 'yo-yo' },
      { c: '🪁', n: 'kite' },
      { c: '🪂', n: 'parachute' },
      { c: '🪃', n: 'boomerang' },
      { c: '🪄', n: 'magic wand' },
      { c: '🪅', n: 'pinata' },
      { c: '🪆', n: 'nesting dolls' },
      { c: '🪇', n: 'maracas' },
      { c: '🪈', n: 'flute' },
      { c: '🪉', n: 'harp' },
      { c: '🪏', n: 'shovel' },
      { c: '🪐', n: 'ringed planet' },
      { c: '🪑', n: 'chair' },
      { c: '🪒', n: 'razor' },
      { c: '🪓', n: 'axe' },
      { c: '🪔', n: 'diya lamp' },
      { c: '🪕', n: 'banjo' },
      { c: '🪖', n: 'military helmet' },
      { c: '🪗', n: 'accordion' },
      { c: '🪘', n: 'long drum' },
      { c: '🪙', n: 'coin' },
      { c: '🪚', n: 'carpentry saw' },
      { c: '🪛', n: 'screwdriver' },
      { c: '🪜', n: 'ladder' },
      { c: '🪝', n: 'hook' },
      { c: '🪞', n: 'mirror' },
      { c: '🪟', n: 'window' },
      { c: '🪠', n: 'plunger' },
      { c: '🪡', n: 'sewing needle' },
      { c: '🪢', n: 'knot' },
      { c: '🪣', n: 'bucket' },
      { c: '🪤', n: 'mouse trap' },
      { c: '🪥', n: 'toothbrush' },
      { c: '🪦', n: 'headstone' },
      { c: '🪧', n: 'placard' },
      { c: '🪨', n: 'rock' },
      { c: '🪩', n: 'mirror ball' },
      { c: '⌚', n: 'watch' },
      { c: '⌛', n: 'hourglass' },
      { c: '☎', n: 'black telephone' },
      { c: '💋', n: 'kiss mark' },
      { c: '💌', n: 'love letter' },
      { c: '💍', n: 'ring' },
      { c: '💎', n: 'gem stone' },
      { c: '💏', n: 'kiss' },
      { c: '💐', n: 'bouquet' },
      { c: '💑', n: 'couple with heart' },
      { c: '💒', n: 'wedding' },
      { c: '💓', n: 'beating heart' },
      { c: '💔', n: 'broken heart' },
      { c: '💕', n: 'two hearts' },
      { c: '💖', n: 'sparkling heart' },
      { c: '💗', n: 'growing heart' },
      { c: '💘', n: 'heart with arrow' },
      { c: '💙', n: 'blue heart' },
      { c: '💚', n: 'green heart' },
      { c: '💛', n: 'yellow heart' },
      { c: '💜', n: 'purple heart' },
      { c: '💝', n: 'heart with ribbon' },
      { c: '💞', n: 'revolving hearts' },
      { c: '💟', n: 'heart decoration' },
    ],
  },
  {
    label: 'Symbols',
    items: [
      { c: '❤', n: 'heavy black heart' },
      { c: '✅', n: 'white heavy check mark' },
      { c: '✔', n: 'heavy check mark' },
      { c: '✨', n: 'sparkles' },
      { c: '❌', n: 'cross mark' },
      { c: '❎', n: 'negative squared cross mark' },
      { c: '❓', n: 'black question mark ornament' },
      { c: '❔', n: 'white question mark ornament' },
      { c: '❕', n: 'white exclamation mark ornament' },
      { c: '❖', n: 'black diamond minus white x' },
      { c: '❗', n: 'heavy exclamation mark symbol' },
      { c: '➕', n: 'heavy plus sign' },
      { c: '➖', n: 'heavy minus sign' },
      { c: '➗', n: 'heavy division sign' },
      { c: '⭐', n: 'white medium star' },
      { c: '⭕', n: 'heavy large circle' },
      { c: '⬛', n: 'black large square' },
      { c: '⬜', n: 'white large square' },
      { c: '⚡', n: 'high voltage sign' },
      { c: '☔', n: 'umbrella with rain drops' },
      { c: '☕', n: 'hot beverage' },
      { c: '♈', n: 'aries' },
      { c: '♉', n: 'taurus' },
      { c: '♊', n: 'gemini' },
      { c: '♋', n: 'cancer' },
      { c: '♌', n: 'leo' },
      { c: '♍', n: 'virgo' },
      { c: '♎', n: 'libra' },
      { c: '♏', n: 'scorpius' },
      { c: '♐', n: 'sagittarius' },
      { c: '♑', n: 'capricorn' },
      { c: '♒', n: 'aquarius' },
      { c: '♓', n: 'pisces' },
      { c: '♿', n: 'wheelchair symbol' },
      { c: '⚓', n: 'anchor' },
      { c: '⚪', n: 'medium white circle' },
      { c: '⚫', n: 'medium black circle' },
      { c: '⛄', n: 'snowman without snow' },
      { c: '⛅', n: 'sun behind cloud' },
      { c: '⛔', n: 'no entry' },
      { c: '⛪', n: 'church' },
      { c: '🆒', n: 'squared cool' },
      { c: '🆓', n: 'squared free' },
      { c: '🆔', n: 'squared id' },
      { c: '🆕', n: 'squared new' },
      { c: '🆖', n: 'squared ng' },
      { c: '🆗', n: 'squared ok' },
      { c: '🆘', n: 'squared sos' },
      { c: '🆙', n: 'squared up with exclamation mark' },
      { c: '🆚', n: 'squared vs' },
    ],
  },
  {
    label: 'Flags',
    items: [
      { c: '🇦🇩', n: 'flag ad' },
      { c: '🇦🇪', n: 'flag ae' },
      { c: '🇦🇫', n: 'flag af' },
      { c: '🇦🇬', n: 'flag ag' },
      { c: '🇦🇱', n: 'flag al' },
      { c: '🇦🇲', n: 'flag am' },
      { c: '🇦🇴', n: 'flag ao' },
      { c: '🇦🇷', n: 'flag ar' },
      { c: '🇦🇹', n: 'flag at' },
      { c: '🇦🇺', n: 'flag au' },
      { c: '🇦🇿', n: 'flag az' },
      { c: '🇧🇦', n: 'flag ba' },
      { c: '🇧🇧', n: 'flag bb' },
      { c: '🇧🇩', n: 'flag bd' },
      { c: '🇧🇪', n: 'flag be' },
      { c: '🇧🇫', n: 'flag bf' },
      { c: '🇧🇬', n: 'flag bg' },
      { c: '🇧🇭', n: 'flag bh' },
      { c: '🇧🇮', n: 'flag bi' },
      { c: '🇧🇯', n: 'flag bj' },
      { c: '🇧🇳', n: 'flag bn' },
      { c: '🇧🇴', n: 'flag bo' },
      { c: '🇧🇷', n: 'flag br' },
      { c: '🇧🇸', n: 'flag bs' },
      { c: '🇧🇹', n: 'flag bt' },
      { c: '🇧🇼', n: 'flag bw' },
      { c: '🇧🇾', n: 'flag by' },
      { c: '🇧🇿', n: 'flag bz' },
      { c: '🇨🇦', n: 'flag ca' },
      { c: '🇨🇩', n: 'flag cd' },
      { c: '🇨🇫', n: 'flag cf' },
      { c: '🇨🇬', n: 'flag cg' },
      { c: '🇨🇭', n: 'flag ch' },
      { c: '🇨🇮', n: 'flag ci' },
      { c: '🇨🇱', n: 'flag cl' },
      { c: '🇨🇲', n: 'flag cm' },
      { c: '🇨🇳', n: 'flag cn' },
      { c: '🇨🇴', n: 'flag co' },
      { c: '🇨🇷', n: 'flag cr' },
      { c: '🇨🇺', n: 'flag cu' },
      { c: '🇨🇻', n: 'flag cv' },
      { c: '🇨🇾', n: 'flag cy' },
      { c: '🇨🇿', n: 'flag cz' },
      { c: '🇩🇪', n: 'flag de' },
      { c: '🇩🇯', n: 'flag dj' },
      { c: '🇩🇰', n: 'flag dk' },
      { c: '🇩🇲', n: 'flag dm' },
      { c: '🇩🇴', n: 'flag do' },
      { c: '🇩🇿', n: 'flag dz' },
      { c: '🇪🇨', n: 'flag ec' },
      { c: '🇪🇪', n: 'flag ee' },
      { c: '🇪🇬', n: 'flag eg' },
      { c: '🇪🇷', n: 'flag er' },
      { c: '🇪🇸', n: 'flag es' },
      { c: '🇪🇹', n: 'flag et' },
      { c: '🇫🇮', n: 'flag fi' },
      { c: '🇫🇯', n: 'flag fj' },
      { c: '🇫🇲', n: 'flag fm' },
      { c: '🇫🇷', n: 'flag fr' },
      { c: '🇬🇦', n: 'flag ga' },
      { c: '🇬🇧', n: 'flag gb' },
      { c: '🇬🇩', n: 'flag gd' },
      { c: '🇬🇪', n: 'flag ge' },
      { c: '🇬🇭', n: 'flag gh' },
      { c: '🇬🇲', n: 'flag gm' },
      { c: '🇬🇳', n: 'flag gn' },
      { c: '🇬🇶', n: 'flag gq' },
      { c: '🇬🇷', n: 'flag gr' },
      { c: '🇬🇹', n: 'flag gt' },
      { c: '🇬🇼', n: 'flag gw' },
      { c: '🇬🇾', n: 'flag gy' },
      { c: '🇭🇳', n: 'flag hn' },
      { c: '🇭🇷', n: 'flag hr' },
      { c: '🇭🇹', n: 'flag ht' },
      { c: '🇭🇺', n: 'flag hu' },
      { c: '🇮🇩', n: 'flag id' },
      { c: '🇮🇪', n: 'flag ie' },
      { c: '🇮🇱', n: 'flag il' },
      { c: '🇮🇳', n: 'flag in' },
      { c: '🇮🇶', n: 'flag iq' },
      { c: '🇮🇷', n: 'flag ir' },
      { c: '🇮🇸', n: 'flag is' },
      { c: '🇮🇹', n: 'flag it' },
      { c: '🇯🇲', n: 'flag jm' },
      { c: '🇯🇴', n: 'flag jo' },
      { c: '🇯🇵', n: 'flag jp' },
      { c: '🇰🇪', n: 'flag ke' },
      { c: '🇰🇬', n: 'flag kg' },
      { c: '🇰🇭', n: 'flag kh' },
      { c: '🇰🇮', n: 'flag ki' },
      { c: '🇰🇲', n: 'flag km' },
      { c: '🇰🇳', n: 'flag kn' },
      { c: '🇰🇵', n: 'flag kp' },
      { c: '🇰🇷', n: 'flag kr' },
      { c: '🇰🇼', n: 'flag kw' },
      { c: '🇰🇿', n: 'flag kz' },
      { c: '🇱🇦', n: 'flag la' },
      { c: '🇱🇧', n: 'flag lb' },
      { c: '🇱🇨', n: 'flag lc' },
      { c: '🇱🇮', n: 'flag li' },
      { c: '🇱🇰', n: 'flag lk' },
      { c: '🇱🇷', n: 'flag lr' },
      { c: '🇱🇸', n: 'flag ls' },
      { c: '🇱🇹', n: 'flag lt' },
      { c: '🇱🇺', n: 'flag lu' },
      { c: '🇱🇻', n: 'flag lv' },
      { c: '🇱🇾', n: 'flag ly' },
      { c: '🇲🇦', n: 'flag ma' },
      { c: '🇲🇨', n: 'flag mc' },
      { c: '🇲🇩', n: 'flag md' },
      { c: '🇲🇪', n: 'flag me' },
      { c: '🇲🇬', n: 'flag mg' },
      { c: '🇲🇭', n: 'flag mh' },
      { c: '🇲🇰', n: 'flag mk' },
      { c: '🇲🇱', n: 'flag ml' },
      { c: '🇲🇲', n: 'flag mm' },
      { c: '🇲🇳', n: 'flag mn' },
      { c: '🇲🇷', n: 'flag mr' },
      { c: '🇲🇹', n: 'flag mt' },
      { c: '🇲🇺', n: 'flag mu' },
      { c: '🇲🇻', n: 'flag mv' },
      { c: '🇲🇼', n: 'flag mw' },
      { c: '🇲🇽', n: 'flag mx' },
      { c: '🇲🇾', n: 'flag my' },
      { c: '🇲🇿', n: 'flag mz' },
      { c: '🇳🇦', n: 'flag na' },
      { c: '🇳🇪', n: 'flag ne' },
      { c: '🇳🇬', n: 'flag ng' },
      { c: '🇳🇮', n: 'flag ni' },
      { c: '🇳🇱', n: 'flag nl' },
      { c: '🇳🇴', n: 'flag no' },
      { c: '🇳🇵', n: 'flag np' },
      { c: '🇳🇷', n: 'flag nr' },
      { c: '🇳🇿', n: 'flag nz' },
      { c: '🇴🇲', n: 'flag om' },
      { c: '🇵🇦', n: 'flag pa' },
      { c: '🇵🇪', n: 'flag pe' },
      { c: '🇵🇬', n: 'flag pg' },
      { c: '🇵🇭', n: 'flag ph' },
      { c: '🇵🇰', n: 'flag pk' },
      { c: '🇵🇱', n: 'flag pl' },
      { c: '🇵🇹', n: 'flag pt' },
      { c: '🇵🇼', n: 'flag pw' },
      { c: '🇵🇾', n: 'flag py' },
      { c: '🇶🇦', n: 'flag qa' },
      { c: '🇷🇴', n: 'flag ro' },
      { c: '🇷🇸', n: 'flag rs' },
      { c: '🇷🇺', n: 'flag ru' },
      { c: '🇷🇼', n: 'flag rw' },
      { c: '🇸🇦', n: 'flag sa' },
      { c: '🇸🇧', n: 'flag sb' },
      { c: '🇸🇨', n: 'flag sc' },
      { c: '🇸🇩', n: 'flag sd' },
      { c: '🇸🇪', n: 'flag se' },
      { c: '🇸🇬', n: 'flag sg' },
      { c: '🇸🇮', n: 'flag si' },
      { c: '🇸🇰', n: 'flag sk' },
      { c: '🇸🇱', n: 'flag sl' },
      { c: '🇸🇲', n: 'flag sm' },
      { c: '🇸🇳', n: 'flag sn' },
      { c: '🇸🇴', n: 'flag so' },
      { c: '🇸🇷', n: 'flag sr' },
      { c: '🇸🇸', n: 'flag ss' },
      { c: '🇸🇹', n: 'flag st' },
      { c: '🇸🇻', n: 'flag sv' },
      { c: '🇸🇾', n: 'flag sy' },
      { c: '🇸🇿', n: 'flag sz' },
      { c: '🇹🇩', n: 'flag td' },
      { c: '🇹🇬', n: 'flag tg' },
      { c: '🇹🇭', n: 'flag th' },
      { c: '🇹🇯', n: 'flag tj' },
      { c: '🇹🇱', n: 'flag tl' },
      { c: '🇹🇲', n: 'flag tm' },
      { c: '🇹🇳', n: 'flag tn' },
      { c: '🇹🇴', n: 'flag to' },
      { c: '🇹🇷', n: 'flag tr' },
      { c: '🇹🇹', n: 'flag tt' },
      { c: '🇹🇻', n: 'flag tv' },
      { c: '🇹🇿', n: 'flag tz' },
      { c: '🇺🇦', n: 'flag ua' },
      { c: '🇺🇬', n: 'flag ug' },
      { c: '🇺🇸', n: 'flag us' },
      { c: '🇺🇾', n: 'flag uy' },
      { c: '🇺🇿', n: 'flag uz' },
      { c: '🇻🇦', n: 'flag va' },
      { c: '🇻🇨', n: 'flag vc' },
      { c: '🇻🇪', n: 'flag ve' },
      { c: '🇻🇳', n: 'flag vn' },
      { c: '🇻🇺', n: 'flag vu' },
      { c: '🇼🇸', n: 'flag ws' },
      { c: '🇾🇪', n: 'flag ye' },
      { c: '🇿🇦', n: 'flag za' },
      { c: '🇿🇲', n: 'flag zm' },
      { c: '🇿🇼', n: 'flag zw' },
    ],
  },
];
