# Generated by Django 6.0.2 on 2026-09-05 07:56

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instruments', '0001_initial'),
        ('wallet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoiPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank for an open-ended top tier.', max_digits=18, null=True)),
                ('tenure_months', models.PositiveIntegerField(default=12, help_text='How many monthly payouts this plan runs for.')),
                ('return_principal_at_maturity', models.BooleanField(default=True)),
                ('allow_early_exit', models.BooleanField(default=False)),
                ('early_exit_penalty_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'roi_plans',
                'ordering': ['display_order', 'min_amount'],
            },
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('principal', models.DecimalField(decimal_places=2, max_digits=18)),
                ('plan_snapshot', models.JSONField(default=dict, help_text="Frozen plan terms: {tenure_months, months: {'1': '1.500', ...}}")),
                ('start_date', models.DateTimeField(db_index=True)),
                ('maturity_date', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('matured', 'Matured'), ('cancelled', 'Cancelled')], db_index=True, default='active', max_length=20)),
                ('months_paid', models.PositiveIntegerField(default=0)),
                ('total_roi_paid', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('principal_released', models.BooleanField(default=False)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('instrument', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investments', to='instruments.instrument')),
                ('source_deposit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investments', to='wallet.deposit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investments', to='investments.roiplan')),
            ],
            options={
                'db_table': 'investments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoiPlanMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_index', models.PositiveIntegerField(help_text='1 = first month after the deposit.')),
                ('percent', models.DecimalField(decimal_places=3, help_text='Percent of the original principal paid in this month.', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='months', to='investments.roiplan')),
            ],
            options={
                'db_table': 'roi_plan_months',
                'ordering': ['plan', 'month_index'],
            },
        ),
        migrations.CreateModel(
            name='RoiPayout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month_index', models.PositiveIntegerField()),
                ('percent', models.DecimalField(decimal_places=3, max_digits=6)),
                ('base_amount', models.DecimalField(decimal_places=2, help_text='Principal the percent applied to.', max_digits=18)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('due_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('skipped', 'Skipped'), ('failed', 'Failed')], default='paid', max_length=20)),
                ('credited_to', models.CharField(default='wallet', help_text="'wallet' (withdrawable) or 'principal' (compounded).", max_length=20)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='investments.investment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roi_payouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'roi_payouts',
                'ordering': ['-due_at'],
                'constraints': [models.UniqueConstraint(fields=('investment', 'month_index'), name='uniq_investment_month_payout')],
            },
        ),
        migrations.AddIndex(
            model_name='investment',
            index=models.Index(fields=['status', 'start_date'], name='investments_status_ef11ad_idx'),
        ),
        migrations.AddConstraint(
            model_name='roiplanmonth',
            constraint=models.UniqueConstraint(fields=('plan', 'month_index'), name='uniq_plan_month'),
        ),
    ]
