# Generated by Django 6.0.2 on 2026-09-07 15:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sender', models.CharField(choices=[('user', 'Member'), ('admin', 'Administrator')], db_index=True, max_length=10)),
                ('body', models.TextField()),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, help_text='Who wrote it. Differs from `member` on an admin reply.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(help_text='The member whose thread this message belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='support_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'support_messages',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['member', 'created_at'], name='support_mes_member__93ca4e_idx'), models.Index(fields=['sender', 'read_at'], name='support_mes_sender_92fba4_idx')],
            },
        ),
    ]
