# Generated by Django 6.0.2 on 2026-09-07 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportmessage',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='forwarded',
            field=models.BooleanField(default=False, help_text='Carried over from another conversation.'),
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='reactions',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='reply_to',
            field=models.ForeignKey(blank=True, help_text='The message this one quotes.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='support.supportmessage'),
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='starred_by',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
